# Generated by Django 5.0.1 on 2024-10-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_skill_profile_availability_profile_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forgot_password_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
