# Generated by Django 5.0.2 on 2024-10-02 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_job_proposal'),
        ('home', '0006_profile_forgot_password_token'),
    ]

    operations = [
    ]
