# Generated by Django 5.0.1 on 2024-10-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_merge_20241003_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='job',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='freelancer',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Proposal',
        ),
    ]
