# Generated by Django 5.0.1 on 2024-10-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_proposal_job_remove_proposal_freelancer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='availability',
            field=models.CharField(choices=[('full-time', 'Full-Time'), ('part-time', 'Part-Time'), ('freelance', 'Freelance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='skills',
            field=models.ManyToManyField(blank=True, to='home.skill'),
        ),
    ]
