# Generated by Django 5.0.1 on 2024-10-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_freelancer_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='forgot_password_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rating',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('freelancer', 'Freelancer'), ('client', 'Client')], default='client', max_length=10),
        ),
        migrations.DeleteModel(
            name='Freelancer',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
