# Generated by Django 5.0.2 on 2024-10-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_skill_profile_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
