# Generated by Django 5.0.2 on 2024-10-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_profile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_created',
            field=models.BooleanField(default=False),
        ),
    ]
