# Generated by Django 5.0.2 on 2024-10-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_profile_account_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fullname',
            field=models.TextField(blank=True, null=True),
        ),
    ]
