# Generated by Django 5.0.2 on 2024-10-06 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_profile_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fullname',
            new_name='experience',
        ),
    ]
