# Generated by Django 5.0.2 on 2024-10-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_job_deadline_alter_job_skills_required_and_more'),
        ('home', '0017_chat_alter_job_created_at_message'),
    ]

    operations = [
    ]
