# Generated by Django 5.0.2 on 2024-10-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_message_chat_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
