# Generated by Django 5.0.2 on 2024-10-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_profile_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
