# Generated by Django 5.0.2 on 2024-10-26 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_category_freelancer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to='home.profile'),
        ),
    ]
