# Generated by Django 5.0.2 on 2024-10-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_freelancer_experience_alter_job_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='client',
            field=models.CharField(max_length=255),
        ),
    ]
