# Generated by Django 5.0.2 on 2025-03-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='disapproval_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
