# Generated by Django 5.0.2 on 2025-03-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_userprofile_disapproval_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_type', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
