# Generated by Django 5.0.2 on 2025-03-13 00:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_crimerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimerecord',
            name='date',
        ),
        migrations.RemoveField(
            model_name='crimerecord',
            name='location',
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='status',
            field=models.CharField(choices=[('Solved', 'Solved'), ('Unsolved', 'Unsolved'), ('Ongoing', 'Ongoing')], default='Ongoing', max_length=50),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='crimerecord',
            name='crime_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crimerecord',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crimerecord',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
