# Generated by Django 5.0.2 on 2025-03-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_remove_crimerecord_date_remove_crimerecord_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimerecord',
            name='crime_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='crime_safe_score',
            field=models.FloatField(default=100.0),
        ),
    ]
