# Generated by Django 5.0.2 on 2025-03-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_crimerecord_crime_count_crimerecord_crime_safe_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('video', models.FileField(upload_to='crime_videos/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Assigned', 'Assigned')], default='Pending', max_length=10)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
