# Generated by Django 5.0.2 on 2025-03-19 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_crimereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereport',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='crime_videos/'),
        ),
        migrations.CreateModel(
            name='CrimeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='crime_images/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.crimereport')),
            ],
        ),
    ]
