# Generated by Django 5.0.2 on 2025-03-19 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_crimereport_video_crimeimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimereport',
            name='latitude',
        ),
        migrations.AddField(
            model_name='crimereport',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='crime_images/'),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='location',
            field=models.CharField(default='Unknown Location', max_length=500),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='CrimeImage',
        ),
    ]
