# Generated by Django 5.0.2 on 2025-03-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_remove_crimereport_latitude_crimereport_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimereport',
            name='images',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='location',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='user',
        ),
        migrations.AddField(
            model_name='crimereport',
            name='address',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='photos',
            field=models.FileField(blank=True, null=True, upload_to='crime_photos/'),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
