# Generated by Django 5.0.2 on 2025-03-20 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_crimereport_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimereport',
            name='photos',
        ),
        migrations.CreateModel(
            name='CrimePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='photos/')),
                ('crime_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='home.crimereport')),
            ],
        ),
    ]
