# Generated by Django 5.0.2 on 2025-03-20 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_remove_crimereport_photos_crimephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.userprofile'),
        ),
    ]
