# Generated by Django 5.0.2 on 2025-03-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_crimereport_reported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='severity_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
