# Generated by Django 5.0.2 on 2025-04-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_crimereport_severity_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='liveness_frame',
            field=models.ImageField(blank=True, null=True, upload_to='liveness_frames/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='liveness_video',
            field=models.FileField(blank=True, null=True, upload_to='liveness_videos/'),
        ),
    ]
