# Generated by Django 5.0.2 on 2025-04-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_userprofile_liveness_frame_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
