# Generated by Django 5.0.2 on 2025-04-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_crimereport_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
