# Generated by Django 5.0.2 on 2025-04-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_crimereport_assigned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='resolution_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Investigation', 'Under Investigation'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
    ]
