# Generated by Django 5.0.2 on 2025-04-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_crimereport_resolution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='first_touched_at',
            field=models.DateTimeField(blank=True, help_text='When officer first opened or updated this report', null=True),
        ),
    ]
