# Generated by Django 5.0.2 on 2025-04-26 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_crimereport_first_touched_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crime_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.crimereport')),
                ('officer', models.ForeignKey(limit_choices_to={'role': 'police'}, on_delete=django.db.models.deletion.CASCADE, to='home.userprofile')),
            ],
        ),
    ]
