# Generated by Django 5.0.2 on 2025-04-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_officerfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
