# Generated by Django 5.0.2 on 2025-04-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_crimereport_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('Junior', 'Junior'), ('Senior', 'Senior'), ('Inspector', 'Inspector')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='specialty',
            field=models.CharField(blank=True, choices=[('Cyber Crime', 'Cyber Crime'), ('Theft', 'Theft'), ('Assault', 'Assault'), ('Fraud', 'Fraud'), ('Narcotics', 'Narcotics'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
