# Generated by Django 5.0.2 on 2025-09-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_userprofile_experience_level_userprofile_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimephoto',
            name='ai_confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crimephoto',
            name='deepfake_suspected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crimephoto',
            name='violence_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crimephoto',
            name='weapon_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='ai_confidence_score',
            field=models.FloatField(blank=True, help_text='0 to 1 probability', null=True),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='ai_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='ai_status',
            field=models.CharField(choices=[('Not Processed', 'Not Processed'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Flagged', 'Flagged')], default='Not Processed', max_length=20),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='deepfake_suspected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='violence_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='weapon_detected',
            field=models.BooleanField(default=False),
        ),
    ]
