# Generated by Django 5.0.2 on 2025-09-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_crimephoto_ai_confidence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimephoto',
            name='is_ai_generated',
            field=models.BooleanField(default=False, help_text='True if detected as AI-generated'),
        ),
        migrations.AddField(
            model_name='crimephoto',
            name='verification_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Flagged', 'Flagged')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='is_ai_generated',
            field=models.BooleanField(default=False, help_text='True if detected as AI-generated'),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='verification_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Flagged', 'Flagged')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='crimephoto',
            name='ai_confidence_score',
            field=models.FloatField(blank=True, help_text='0.0 to 1.0 probability score', null=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='ai_confidence_score',
            field=models.FloatField(blank=True, help_text='0.0 to 1.0 probability score', null=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='ai_status',
            field=models.CharField(choices=[('Not Processed', 'Not Processed'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='Not Processed', max_length=20),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='resolution_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Investigation', 'Under Investigation'), ('Resolved', 'Resolved')], default='Pending', max_length=30),
        ),
    ]
