# Generated by Django 4.2.24 on 2025-09-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_crimephoto_is_ai_generated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimereport',
            name='ai_confidence_score',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='ai_processed_at',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='deepfake_suspected',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='is_ai_generated',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='verification_status',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='violence_detected',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='weapon_detected',
        ),
        migrations.AddField(
            model_name='crimereport',
            name='ai_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='ai_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
