# Generated by Django 4.2.24 on 2025-09-25 16:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_remove_crimereport_ai_confidence_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lgd_name', models.CharField(max_length=100, unique=True)),
                ('lgd_code', models.IntegerField(unique=True)),
                ('townname', models.CharField(default='Thane', max_length=100)),
                ('state', models.CharField(default='Maharashtra', max_length=50)),
                ('st_area', models.FloatField(blank=True, null=True)),
                ('st_length', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='crimerecord',
            name='city',
        ),
        migrations.RemoveField(
            model_name='crimerecord',
            name='crime_count',
        ),
        migrations.RemoveField(
            model_name='crimerecord',
            name='crime_safe_score',
        ),
        migrations.RemoveField(
            model_name='crimerecord',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='crimerecord',
            name='district',
        ),
        migrations.RemoveField(
            model_name='crimerecord',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='crimerecord',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='crimerecord',
            name='state',
        ),
        migrations.RemoveField(
            model_name='crimerecord',
            name='status',
        ),
        migrations.RemoveField(
            model_name='crimerecord',
            name='year',
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='date_reported',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crimerecord',
            name='crime_type',
            field=models.CharField(blank=True, choices=[('theft', 'Theft'), ('assault', 'Assault'), ('fraud', 'Fraud'), ('other', 'Other'), ('domestic_violence', 'Domestic Violence'), ('kidnapping', 'Kidnapping'), ('drug_offense', 'Drug Offense'), ('robbery', 'Robbery'), ('cheating', 'Cheating'), ('cybercrime', 'Cybercrime'), ('murder', 'Murder'), ('burglary', 'Burglary'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crimes', to='home.ward'),
        ),
    ]
