# Generated by Django 4.2.24 on 2025-10-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_policestation_remove_userprofile_station_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_on_duty',
            field=models.BooleanField(default=True),
        ),
    ]
