# Generated by Django 4.2.24 on 2025-10-04 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_userprofile_is_on_duty'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crime_reports', to='home.policestation'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('police', 'Police'), ('sho', 'SHO')], max_length=10, null=True),
        ),
    ]
