# Generated by Django 4.2.24 on 2025-10-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_crimereport_station_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contacts',
            field=models.TextField(blank=True, help_text='Comma-separated phone numbers to notify during SOS', null=True),
        ),
    ]
