# Generated by Django 4.2.24 on 2026-01-21 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_remove_userprofile_emergency_contacts_trustedcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligenceInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('baseline_avg', models.FloatField()),
                ('recent_count', models.IntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=150, null=True)),
                ('author', models.CharField(blank=True, max_length=150, null=True)),
                ('url', models.URLField(unique=True)),
                ('published_at', models.DateTimeField()),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('state', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(default='India', max_length=120)),
                ('crime_type', models.CharField(blank=True, max_length=120, null=True)),
                ('risk_score', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=0.0)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsCrimeCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historical_trend_change', models.FloatField()),
                ('predicted_risk', models.FloatField()),
                ('deviation_score', models.FloatField()),
                ('matches_prediction', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.newsarticle')),
            ],
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['city'], name='home_newsar_city_01b2cf_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['crime_type'], name='home_newsar_crime_t_a81550_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['published_at'], name='home_newsar_publish_10377b_idx'),
        ),
        migrations.AddField(
            model_name='intelligenceinsight',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='home.newsarticle'),
        ),
    ]
