# Generated by Django 4.2.24 on 2026-01-21 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_intelligenceinsight_newsarticle_newscrimecorrelation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscrimecorrelation',
            name='historical_trend_change',
        ),
        migrations.AddField(
            model_name='newscrimecorrelation',
            name='historical_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='newscrimecorrelation',
            name='recent_trend',
            field=models.IntegerField(default=0, help_text='Short-term trend indicator (e.g., -1, 0, 1)'),
        ),
        migrations.AddField(
            model_name='newscrimecorrelation',
            name='risk_level',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='newscrimecorrelation',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correlation', to='home.newsarticle'),
        ),
        migrations.AlterField(
            model_name='newscrimecorrelation',
            name='deviation_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='newscrimecorrelation',
            name='matches_prediction',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newscrimecorrelation',
            name='predicted_risk',
            field=models.FloatField(default=0.0),
        ),
    ]
