# Generated by Django 4.2.24 on 2026-01-21 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_remove_newscrimecorrelation_historical_trend_change_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsActionInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(max_length=50)),
                ('action_text', models.TextField()),
                ('priority', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='home.newsarticle')),
            ],
        ),
    ]
