# Generated by Django 4.2.24 on 2026-01-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_newsactioninsight'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='severity_score',
            field=models.FloatField(default=0.0),
        ),
    ]
