# Generated by Django 4.2.24 on 2026-01-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_newsarticle_severity_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='area',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
