# Generated by Django 4.2.24 on 2026-01-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_newsarticle_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='area',
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='severity_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
