# Generated by Django 4.2.24 on 2026-01-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_remove_newsarticle_area_alter_newsarticle_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='area',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
