# Generated by Django 4.2.24 on 2026-03-29 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0064_newsarticle_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_case_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='centroid_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='centroid_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='resolution_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Investigation', 'Under Investigation'), ('Awaiting Approval', 'Awaiting Approval'), ('Resolved', 'Resolved')], default='Pending', max_length=30),
        ),
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('notified', 'Officers Notified'), ('acknowledged', 'Officer Acknowledged'), ('escalated', 'Escalated to SHO'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled by Citizen')], default='pending', max_length=20)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_acknowledged', to='home.userprofile')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to=settings.AUTH_USER_MODEL)),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_escalations', to='home.userprofile')),
                ('notified_officers', models.ManyToManyField(blank=True, related_name='sos_notifications', to='home.userprofile')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.ward')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('action_taken', models.TextField()),
                ('evidence_notes', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('sho_approved', models.BooleanField(null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('crime_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_report', to='home.crimereport')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.userprofile')),
            ],
        ),
    ]
