# Generated by Django 4.2.24 on 2026-03-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_userprofile_active_case_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='lgd_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
