# Generated by Django 4.2.24 on 2026-03-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_alter_ward_lgd_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsIntel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('source', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('crime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.TextField()),
                ('risk_level', models.CharField(max_length=20)),
                ('suggested_action', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
