# Generated by Django 4.2.24 on 2026-03-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_newsintel'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsintel',
            name='priority_score',
            field=models.IntegerField(default=0),
        ),
    ]
