# Generated by Django 4.2.24 on 2026-03-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_newsintel_priority_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsintel',
            name='author',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='newsintel',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsintel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsintel',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsintel',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsintel',
            name='source',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='newsintel',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='newsintel',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
