# Generated by Django 4.2.24 on 2026-04-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_newsintel_author_newsintel_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsintel',
            name='impact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsintel',
            name='insight',
            field=models.TextField(blank=True, null=True),
        ),
    ]
