# Generated by Django 4.2.24 on 2026-04-03 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0070_newsintel_impact_newsintel_insight'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(default='Anonymous', max_length=100)),
                ('incident_text', models.TextField()),
                ('crime_type', models.CharField(blank=True, max_length=50)),
                ('severity', models.CharField(default='medium', max_length=20)),
                ('severity_score', models.FloatField(default=5.0)),
                ('summary', models.TextField(blank=True)),
                ('dispatch_recommendation', models.TextField(blank=True)),
                ('escalation_probability', models.IntegerField(default=0)),
                ('escalation_reason', models.TextField(blank=True)),
                ('area_risk_score', models.FloatField(default=5.0)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('ward', models.CharField(blank=True, max_length=100)),
                ('landmark', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('ai_correct', models.BooleanField(blank=True, null=True)),
                ('actual_severity', models.CharField(blank=True, max_length=20)),
                ('actual_response_time', models.IntegerField(blank=True, null=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_alerts', to='home.userprofile')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
