# Generated by Django 4.2.24 on 2026-04-04 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0071_incidentalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.RenameField(
            model_name='incidentalert',
            old_name='responded_at',
            new_name='accepted_at',
        ),
        migrations.RenameField(
            model_name='incidentalert',
            old_name='actual_response_time',
            new_name='citizen_rating',
        ),
        migrations.AddField(
            model_name='incidentalert',
            name='ai_confidence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incidentalert',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentalert',
            name='citizen_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incidentalert',
            name='enroute_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentalert',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentalert',
            name='escalated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_alerts', to='home.userprofile'),
        ),
        migrations.AddField(
            model_name='incidentalert',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidentalert',
            name='resolution_time',
            field=models.IntegerField(blank=True, help_text='Seconds from created to resolved', null=True),
        ),
        migrations.AddField(
            model_name='incidentalert',
            name='response_time',
            field=models.IntegerField(blank=True, help_text='Seconds from created to accepted', null=True),
        ),
        migrations.AddField(
            model_name='incidentalert',
            name='rule_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidentalert',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_alerts', to='home.policestation'),
        ),
        migrations.AddField(
            model_name='incidentalert',
            name='time_risk',
            field=models.CharField(default='day', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidentalert',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to='home.userprofile'),
        ),
        migrations.AlterField(
            model_name='incidentalert',
            name='crime_type',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='incidentalert',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidentalert',
            name='reporter_name',
            field=models.CharField(default='Anonymous', max_length=120),
        ),
        migrations.AlterField(
            model_name='incidentalert',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('enroute', 'En Route'), ('arrived', 'Arrived'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('escalated', 'Escalated to SHO')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='incidentalert',
            index=models.Index(fields=['status'], name='home_incide_status_17f374_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentalert',
            index=models.Index(fields=['assigned_officer', 'status'], name='home_incide_assigne_19a6f3_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentalert',
            index=models.Index(fields=['created_at'], name='home_incide_created_5c09a5_idx'),
        ),
        migrations.AddField(
            model_name='incidenttimeline',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidenttimeline',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='home.incidentalert'),
        ),
    ]
