# Generated by Django 4.2.24 on 2026-04-04 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0072_incidenttimeline_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policestation',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['seniority', 'user__first_name']},
        ),
        migrations.RemoveIndex(
            model_name='incidentalert',
            name='home_incide_status_17f374_idx',
        ),
        migrations.RemoveIndex(
            model_name='incidentalert',
            name='home_incide_assigne_19a6f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='incidentalert',
            name='home_incide_created_5c09a5_idx',
        ),
        migrations.RemoveField(
            model_name='incidentalert',
            name='resolution_time',
        ),
        migrations.RemoveField(
            model_name='incidentalert',
            name='response_time',
        ),
        migrations.RemoveField(
            model_name='incidentalert',
            name='rule_override',
        ),
        migrations.RemoveField(
            model_name='incidentalert',
            name='time_risk',
        ),
        migrations.AddField(
            model_name='incidentalert',
            name='reporter_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='incidentalert',
            name='resolution_time_secs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentalert',
            name='response_time_secs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policestation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='policestation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='policestation',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='policestation',
            name='wards',
            field=models.TextField(blank=True, help_text='Comma-separated ward names this station covers'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='seniority',
            field=models.CharField(blank=True, choices=[('constable', 'Constable'), ('head_constable', 'Head Constable'), ('asi', 'ASI'), ('si', 'Sub Inspector'), ('inspector', 'Inspector'), ('dsp', 'DSP')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='incidentalert',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to='home.userprofile'),
        ),
        migrations.AlterField(
            model_name='incidentalert',
            name='escalated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_incidents', to='home.userprofile'),
        ),
        migrations.AlterField(
            model_name='incidentalert',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidentalert',
            name='reporter_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='incidentalert',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='home.policestation'),
        ),
        migrations.AlterField(
            model_name='incidentalert',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('enroute', 'En Route'), ('arrived', 'Arrived'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidenttimeline',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('enroute', 'En Route'), ('arrived', 'Arrived'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], max_length=20),
        ),
    ]
