# Generated by Django 4.2.24 on 2026-04-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_alter_policestation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentalert',
            name='citizen_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='incidentalert',
            name='citizen_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
