# Generated by Django 4.2.24 on 2026-04-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_incidentalert_citizen_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=models.URLField(),
        ),
    ]
