# Generated by Django 4.2.24 on 2026-04-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0075_alter_newsarticle_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsintel',
            name='similar_pattern_keywords',
            field=models.JSONField(blank=True, default=list, help_text='Keywords for pattern matching across stories'),
        ),
        migrations.AddField(
            model_name='newsintel',
            name='threat_escalation',
            field=models.CharField(default='no', help_text='AI prediction: will this escalate in 48h? yes/no', max_length=5),
        ),
    ]
