# Generated by Django 4.2.24 on 2026-04-09 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0076_newsintel_similar_pattern_keywords_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investigationreport',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='investigationreport',
            name='summary',
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='ai_case_summary',
            field=models.TextField(blank=True, help_text='Groq-generated case narrative'),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='ai_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='ai_next_steps',
            field=models.TextField(blank=True, help_text='AI-recommended next investigation steps'),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='ai_risk_assessment',
            field=models.TextField(blank=True, help_text='AI assessment: likelihood of conviction, missing evidence'),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='ai_suggested_sections',
            field=models.CharField(blank=True, help_text='AI-suggested IPC sections', max_length=300),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='arrest_details',
            field=models.TextField(blank=True, help_text='Name, age, address, charges for each arrested person'),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='arrests_made',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='case_outcome',
            field=models.CharField(blank=True, choices=[('chargesheet_filed', 'Chargesheet Filed'), ('closure_report', 'Closure Report'), ('referred_to_court', 'Referred to Court'), ('further_investigation', 'Further Investigation Required'), ('pending_forensics', 'Pending Forensics')], max_length=30),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='cctv_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='date_of_occurrence',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='digital_forensics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='evidence_items',
            field=models.JSONField(blank=True, default=list, help_text='[{item_no, description, collection_date, custody_officer, location}]'),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='fir_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='forensic_lab',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='forensic_report_awaited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='forensic_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='incident_summary',
            field=models.TextField(help_text='Factual account: who, what, where, when', null=True),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='ipc_sections',
            field=models.CharField(blank=True, help_text='Comma-separated IPC sections e.g. 302, 376, 420', max_length=300),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='officer_conclusion',
            field=models.TextField(blank=True, help_text="Officer's final conclusion and recommendation"),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='scene_description',
            field=models.TextField(blank=True, help_text='Physical description of the crime scene'),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='sho_comments',
            field=models.TextField(blank=True, help_text='SHO revision instructions or approval notes'),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='site_visited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='site_visited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Review'), ('sho_approved', 'SHO Approved'), ('sho_rejected', 'Returned for Revision'), ('court_ready', 'Court-Ready')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='time_of_occurrence',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='witness_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='investigationreport',
            name='witness_statements',
            field=models.JSONField(blank=True, default=list, help_text='[{name, age, contact, statement_summary, recorded_at}]'),
        ),
        migrations.AlterField(
            model_name='investigationreport',
            name='action_taken',
            field=models.TextField(help_text='Chronological list of every action: visits, interviews, arrests'),
        ),
        migrations.AlterField(
            model_name='investigationreport',
            name='evidence_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='investigationreport',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
