# Generated by Django 4.2.24 on 2026-04-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0077_alter_investigationreport_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('crime_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('wanted', 'Wanted'), ('watch', 'Watch'), ('arrested', 'Arrested')], default='watch', max_length=20)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('ward', models.CharField(max_length=100)),
                ('fir_number', models.CharField(blank=True, max_length=50)),
                ('last_seen', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='suspects/')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
