# Generated by Django 4.2.24 on 2026-04-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0078_suspect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='experience_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='specialty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
