# Generated by Django 4.2.24 on 2026-04-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0081_alter_crimephoto_photos_alter_suspect_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimephoto',
            name='photos',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='suspects/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='liveness_frame',
            field=models.ImageField(blank=True, null=True, upload_to='liveness_frames/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_images/'),
        ),
    ]
