# Generated by Django 4.2.24 on 2026-04-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0082_alter_crimephoto_photos_alter_suspect_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimephoto',
            name='photos',
            field=models.FileField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='suspects/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='id_cards/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='liveness_frame',
            field=models.FileField(blank=True, null=True, upload_to='liveness_frames/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.FileField(blank=True, max_length=20, null=True, upload_to=''),
        ),
    ]
